(function(){
var h=~location.search.indexOf("debug=");function m(a){h&&console.log.apply(console,arguments)}if("web.archive.org"!==location.hostname){n=n||document;p=p||window;q=q||navigator;var t=new r,v=new u;new w};function x(){var a={en:{u:"This website uses cookies",h:"This website, <b>"+location.hostname.replace(/^www\./,"")+"</b>, uses cookies to provide you with the best experience by personalizing content, services, and to measure website usage.",j:"Essentials",i:"Analytics",l:"Marketing",o:"Social Media",g:"OK",f:"MORE INFO",c:"Close"}};this.b=function(){return a[(q.userLanguage||q.language||"en").substr(0,2).toLowerCase()]||a.en}};function w(){function a(a){for(var f=a.length,e=0,k,l,c,d;e<f;)k=a[e++],l=k.nodeName.toLowerCase(),c="img"===l,d="object"===l,!c&&!d&&"iframe"!==l&&"script"!==l||k.getAttribute("data-blocked")||(l=k.src||k.data)&&!b.b(l)&&(k.setAttribute("data-blocked",l),k[d?"data":"src"]=c?"data:image/svg+xml,%3Csvg/%3E":"//javascript:;")}function c(a){var b=n.createElement;n.createElement=function(){var e=b.apply(n,arguments);g.test(e.nodeName.toLowerCase())&&a.observe(e,d);return e};window.Image=function(a,b){var e=
n.createElement("IMG");0<=a&&e.setAttribute("width",a);0<=b&&e.setAttribute("height",b);return e}}var b=v,d={attributes:!0,childList:!0,subtree:!0,characterData:!1,attributeFilter:["data","src"]},g=/img|image|iframe|object|script/;(function(){var b=new MutationObserver(function(b){for(var e=b.length,c=0,d;c<e;)d=b[c++],"childList"===d.type?a(d.addedNodes):"attributes"===d.type&&a([d.target])});c(b);b.observe(n,d)})()};function r(){function a(){var a=n.createElement("DIV");a.innerHTML=f;n.body.appendChild(a).id=b;setTimeout(function(){var b=C.b(),d=(a&&a.getElementsByTagName("FORM"))[0],c=d.elements,e;d.onsubmit=function(){var a=y({a:+c.a.checked,m:+c.m.checked,s:+c.s.checked});n.cookie=escape("pii-consent")+"="+escape(a||"")+"; expires="+(new z(15552E6+ +new z)).toGMTString()+"; path=/; domain="+n.domain;location.reload();return!1};for(e in b)c[e]&&(c[e].checked=!!b[e]);(a&&a.getElementsByTagName("SPAN"))[0].onclick=
function(){a&&a.parentNode&&a.parentNode.removeChild(a)}},0)}var c={a:0,m:0,s:0},b="pii-"+Date.now().toString(36).slice(-5),d=(new x).b(),g=/\s+/g,f="<style>"+("#"+b+",#"+b+" form,#"+b+" p,#"+b+" button,#"+b+" h1{background:#fff;bottom:0;border:0;color:#000;font:normal normal normal 14px/150% arial,sans-serif;margin:0;padding:0;text-align:center;}#"+b+"{box-shadow: 0 0 10px 0 #bbb;padding:1em;position:fixed;width:100%;z-index:9999}#"+b+" span{color:#777;cursor:pointer;font-size:2.4em;position:absolute;right:.8em;top:.6em}#"+
b+" b{font-weight:bold}#"+b+" h1{display:inline-block;font-size:1.5em;font-weight:normal;transform:scale(1,1.05)}#"+b+" p{color:#666;margin:.5em 0}#"+b+" label{display:inline-block;white-space:nowrap}#"+b+" input{margin:.5em .1em .5em .5em;vertical-align:middle}#"+b+" a{color:#48e;text-decoration:none}#"+b+" button{background:#48e;border-radius:2px;box-shadow:0 1px 1px 0 #999;color:#fff;margin-left:1em;min-width:6em;padding:.4em .4em .3em}")+'</style><span title="'+d.c+'">×</span><form><h1>'+d.u+
"</h1><p>"+d.h+'</p><label><input type="checkbox" checked disabled> '+d.j.replace(g,"&nbsp;")+'</label><label><input type="checkbox" name="a"> '+d.i.replace(g,"&nbsp;")+'</label><label><input type="checkbox" name="m"> '+d.l.replace(g,"&nbsp;")+'</label><label><input type="checkbox" name="s"> '+d.o.replace(g,"&nbsp;")+'</label><p><a href="https://pii.zone">'+d.f+'</a><button type="submit">'+d.g+"</button></p></form>";this.b=function(){var a=A(),b=B;if(a&&!a.indexOf("{")&&a.lastIndexOf("}")==a.length-
1)try{b=D(a)}catch(l){}return b||c};var C=this;(function(){E(function(){A()||a();p.openPrivacyConsentSettings=a})})()};function u(){var a=t,c={a:["google-analytics.com","komito.net"],m:["googleadservices.com","connect.facebook.net"],s:["facebook.com","twitter.com","plus.google.com"]};this.b=function(a){b.href=a;var f=b.protocol,g,e;if("data:"!==f||"javascript:"!==f){var k=b.hostname.replace(/^www\./,"");for(e in c)if(!d[e])for(f=c[e],g=f.length;g--;)if((new RegExp(f[g])).test(k))return m("%c[DEBUG] Blocked URL:","color: red;",a),!1}m("%c[DEBUG] Allowed URL:","color: green;",a);return!0};var b=n.createElement("A"),
d=a.b()};var n=document,p=window,q=navigator,B=null;function E(a){var c=p;c.attachEvent?c.attachEvent("onload",a):c.addEventListener("load",a,!1)};function A(){return unescape((n.cookie.match("pii-consent=([^;].+?)(;|$)")||[])[1]||"")};var z=Date;function D(a){return(p.JSON?JSON.parse(a):eval("("+a+")"))||B}var y=p.JSON?JSON.stringify:function(a){var c=typeof a,b=[],d;if("object"!==c||B===a)a="string"===c?'"'+a+'"':""+a;else{var g=(c=Array.isArray)?c(a):"[object Array]"===Object.prototype.toString.call(a);for(d in a){var f=a[d];c=typeof f;"string"===c?f='"'+f+'"':"object"===c&&B!==f&&(f=y(f));b.push((g?"":'"'+d+'":')+f)}a=(g?"[":"{")+b+(g?"]":"}")}return a};
})();
